name: continuous-integration

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:

jobs:

  pre-commit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: pip
    - uses: pre-commit/action@v2.0.0

  tests:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        sphinx: ["~=4.0","~=5.0","~=6.0","~=7.0"]
        include:
        - os: windows-latest
          python-version: 3.8
          sphinx: "~=6.0"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies with Sphinx ${{ matrix.sphinx }}
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade "Sphinx${{ matrix.sphinx }}" -e .[testing]
    - name: Run pytest
      run: |
        pytest --cov=sphinx_design --cov-report=xml --cov-report=term-missing
    - name: Upload to Codecov
      # TODO: Move this to a separate convergence test
      if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest' && matrix.sphinx == '~=6.0'
      uses: codecov/codecov-action@v1
      with:
        name: pytests
        flags: pytests
        file: ./coverage.xml
        fail_ci_if_error: true

  docs-build-format:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        format: [html, latex, man]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[rtd]
    - name: Build documentation
      run: sphinx-build -nW --keep-going -b ${{ matrix.format }} docs/ docs/_build/${{ matrix.format }}

  publish:

    name: Publish to PyPi
    needs: [pre-commit, tests]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: install flit
      run: |
        pip install flit~=3.4
    - name: Build and publish
      run: |
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_KEY }}
